<?php
/**
 * Test class for Testy_Project_Test_ExceptionTest.
 * Generated by PHPUnit on 2011-12-03 at 18:39:21.
 */
class Testy_Project_Test_ExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * Test Exception-Creation
     */
    public function testCreation() {
        $oException = new Testy_Project_Test_Exception('TEST');
        $this->assertEquals('TEST', $oException->getMessage());
        $this->assertInstanceOf('Exception', $oException);
        $this->assertInstanceOf('Testy_Exception', $oException);
    }
}
