<?php
/**
 * Test class for Testy_Project_Test_Runner.
 * Generated by PHPUnit on 2011-12-03 at 18:39:21.
 */
class Testy_Project_Test_RunnerTest extends PHPUnit_Framework_TestCase {
    /**
     * Project name
     *
     * @var string
     */
    const PROJECT_NAME = 'Testy_Test';

    /**
     * @var Testy_Project_Test_Runner
     */
    protected $object;

    /**
     * @var Testy_Project
     */
    protected $oProject;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->oProject = new Testy_Project(self::PROJECT_NAME);
        $this->object = new Testy_Project_Test_Runner($this->oProject, array(
            __FILE__
        ), '.');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test setting repeat
     */
    public function testRepeat() {
        $this->assertInstanceOf('Testy_Project_Test_Runner', $this->object->repeat());
    }

    /**
     * Test running the runnter
     */
    public function testRun() {
        $this->assertInstanceOf('Testy_Project_Test_Runner', $this->object->run());
    }

    /**
     * Test getting the result
     */
    public function testGet() {
        $this->assertEquals('', $this->object->get());
    }
}
