<?php
/**
 * Test class for Testy_Config.
 * Generated by PHPUnit on 2011-12-10 at 20:00:10.
 */
class Testy_ConfigTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Config
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Testy_Config('testy.json.dist');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test config-creation
     */
    public function testGet() {
        $oConfig = $this->object->get();
        $this->assertInstanceOf('stdClass', $oConfig);
    }

    /**
     * Test the update-check
     */
    public function testWasUpdated() {
        $this->object->get();
        $this->assertTrue($this->object->wasUpdated());

        $this->object->get();
        $this->assertFalse($this->object->wasUpdated());
    }

    /**
     * Test that a exception is thrown, if an error occurs
     */
    public function testException() {
        try {
            new Testy_Config();
            $this->fail('An exception should be raised, when creating a config-builder without file');
        }
        catch(Exception $e) {
            $this->assertEquals($e->getMessage(), Testy_Config::CONFIG_ERROR);
        }
    }
}
