<?php

/**
 * Test class for Testy_Watch.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Testy_WatchTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Watch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Testy_Watch();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test simple add call
     */
    public function testAdd() {
        $this->assertInstanceOf('Testy_Watch', $this->object->add($this->getMock('Testy_Project')));
    }

    /**
     * Test the loop-call
     */
    public function testLoop() {
        $this->assertInstanceOf('Testy_Watch', $this->object->loop());
    }
}
