<?php

/**
 * Test class for Testy_Watch.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Testy_WatchTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Watch
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new Testy_Watch();
        $this->assertEmpty($this->_object->getStack());
    }

    /**
     * Test that a disabled project will not be added
     */
    public function testAddNotEnabled() {
        $this->assertInstanceOf('Testy_Watch', $this->_object->add(Tests_Helper_Project::getDisabled()));
        $this->assertEmpty($this->_object->getStack());
    }

    /**
     * Test simple add call and that a added project will be removed
     */
    public function testAddAndRemove() {
        $this->assertInstanceOf('Testy_Watch', $this->_object->add(Tests_Helper_Project::getEnabled()));
        $this->assertNotEmpty($this->_object->getStack());

        $this->assertInstanceOf('Testy_Watch', $this->_object->add(Tests_Helper_Project::getDisabled()));
        $this->assertEmpty($this->_object->getStack());
    }

    /**
     * Test the loop-call
     */
    public function testLoop() {
        $oMock = $this->getMockBuilder('Testy_Util_Parallel_Transport_File')->getMock();
        $this->assertInstanceOf('Testy_Watch', $this->_object->loop($oMock, 2));
    }
}
