<?php
/**
 * Test class for \Testy\TextUI\Command.
 * Generated by PHPUnit on 2011-12-16 at 15:25:52.
 */
namespace Testy\Test\TextUI;

class CommandTest extends \PHPUnit_Framework_TestCase {

    /**
     * The test dummy
     *
     * @var \Testy\TextUI\Command
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new \Testy\TextUI\Command();
    }

    /**
     * Test handleArguments
     *
     * @param  boolean $bExpected
     * @param  array $aArguments
     *
     * @dataProvider handleArgumentsProvider
     */
    public function testHandleArguments($bExpected, $aArguments) {
        try {
            $this->_object->handleArguments($aArguments);
        }
        catch (\Exception $oConfigException) {
            if ($bExpected === true) {
                $this->assertEquals(\Testy\Config::ERROR, $oConfigException->getMessage());
            }
        }

        $aReturn = $this->_object->getArguments();
        $this->assertEquals($bExpected, (empty($aReturn) !== true));
    }

    /**
     * Data-provider for testHandleArguments
     */
    public function handleArgumentsProvider() {
        return array(
            array(
                false,
                array()
            ),
            array(
                false,
                array(
                    '--unknown'
                )
            ),
            array(
                false,
                array(
                    '--verbose'
                )
            ),
            array(
                true,
                array(
                    '--config=test'
                )
            )
        );
    }

    /**
     * Test the usage-string
     */
    public function testShowHelp() {
        $this->expectOutputString(\Testy\TextUI\Command::USAGE . PHP_EOL);
        \Testy\TextUI\Command::showHelp();
    }

    /**
     * Test the usage-string
     */
    public function testShowHelpArgument() {
        $this->expectOutputString(\Testy\TextUI\Command::USAGE . PHP_EOL);
        $aArguments = array(
            '--help'
        );
        $this->assertFalse($this->_object->handleArguments($aArguments));
    }

    /**
     * Test the version-string
     */
    public function testPrintVersionString() {
        $this->expectOutputString(\Testy\TextUI\Command::VERSION . PHP_EOL);
        \Testy\TextUI\Command::printVersionString();
    }

    /**
     * Test the version-string
     */
    public function testPrintVersionStringArgument() {
        $this->expectOutputString(\Testy\TextUI\Command::VERSION . PHP_EOL);
        $aArguments = array(
            '--version'
        );
        $this->assertFalse($this->_object->handleArguments($aArguments));
    }
}
