<?php
/**
 * Test class for \Testy\TextUI\Output.
 * Generated by PHPUnit on 2011-10-22 at 23:06:51.
 */
namespace Testy\Test\TextUI;

class OutputTest extends \PHPUnit_Framework_TestCase {

    const TEST_STRING = 'Testy makes testing easier';

    /**
     * Test the error output
     */
    public function testError() {
        $this->expectOutputString('Error: ' . self::TEST_STRING . PHP_EOL);
        \Testy\TextUI\Output::error(self::TEST_STRING);
    }

    /**
     * Test the info output
     */
    public function testInfo() {
        $this->expectOutputString(self::TEST_STRING . PHP_EOL);
        \Testy\TextUI\Output::info(self::TEST_STRING);
    }

    /**
     * Test the write output
     */
    public function testWrite() {
        $this->expectOutputString(self::TEST_STRING);
        \Testy\TextUI\Output::write(self::TEST_STRING);
    }
}
