<?php
/**
 * Test class for Testy_Util_Parallel_Transport_File.
 * Generated by PHPUnit on 2012-03-24 at 14:59:34.
 */
class Testy_Util_Parallel_Transport_FileTest extends Tests_Util_Parallel_Transport_TestAbstract {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_sTestClass = 'Testy_Util_Parallel_Transport_File';
        parent::setUp();
    }
}
