<?php
/**
 * Test class for Testy_Util_Parallel_Transport_SharedMemory.
 * Generated by PHPUnit on 2012-03-24 at 14:59:34.
 */
abstract class Tests_Util_Parallel_Transport_TestAbstract extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Util_Parallel_TransportInterface
     */
    protected $_object;

    /**
     * The test class
     *
     * @var string
     */
    protected $_sTestClass = '';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        if (class_exists($this->_sTestClass) === true) {
            $this->_object = new $this->_sTestClass();
            $this->assertInstanceOf('Testy_Util_Parallel_TransportInterface', $this->_object);
            $this->assertInstanceOf('Testy_Util_Parallel_TransportInterface', $this->_object->setup(array(
                'dir' => Testy_Util_Parallel_Execute::DIR,
                'server' => 'localhost',
                'port' => 11211
            )));
        }
        else {
            $this->markTestSkipped(sprintf('Test class %s does not exist', $this->_sTestClass));
        }
    }

    /**
     * Test the whole transport
     */
    public function testAll() {
        $sTestVal = uniqid();
        $sTestKey = (int) microtime(true);

        $this->assertFalse($this->_object->read($sTestKey));
        $this->assertInstanceOf($this->_sTestClass, $this->_object->write($sTestKey, $sTestVal));
        $this->assertEquals($sTestVal, $this->_object->read($sTestKey));
        $this->assertInstanceOf($this->_sTestClass, $this->_object->free());
    }
}
