<?php
/**
 * Test class for Testy_Notifier_Dbus.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Testy_Notifier_DbusTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Notifier_Dbus
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new Testy_Notifier_Dbus();
    }

    /**
     * Test simple notify call
     */
    public function testNotify() {
        $this->assertInstanceOf('Testy_AbstractNotifier', $this->_object->notify($this->getMock('Testy_Project'), Testy_AbstractNotifier::SUCCESS, ''));
    }
}
