<?php
/**
 * Test class for Testy_Notifier_Stdout.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Testy_Notifier_StdoutTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Testy_Notifier_Stdout
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Testy_Notifier_Stdout();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test simple add call
     */
    public function testNotify() {
        $this->expectOutputRegex('/Test/');
        $this->assertInstanceOf('Testy_AbstractNotifier', $this->object->notify($this->getMock('Testy_Project'), Testy_AbstractNotifier::SUCCESS, 'Test'));
    }
}
