<?php
/**
 * Test class for Testy_Util_Parallel.
 * Generated by PHPUnit on2011-2012-10-23 at 17:48:39.
 */
class Testy_Util_Parallel_ExecuteTest extends PHPUnit_Framework_TestCase {

    /**
     * The object to test with
     *
     * @var string
     */
    const TEST_MOCK = 'Testy_Project';

    /**
     * @var Testy_Util_Parallel_Execute
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $aStack = array(
            $this->getMock(self::TEST_MOCK),
            $this->getMock(self::TEST_MOCK),
            $this->getMock(self::TEST_MOCK),
            $this->getMock(self::TEST_MOCK)
        );

        $oTransport = $this->getMock('Testy_Util_Parallel_Transport_File');
        $oTransport->expects($this->any())
                   ->method('get')
                   ->will($this->returnValue(self::TEST_MOCK));

        $this->_object = new Testy_Util_Parallel_Execute($aStack, $oTransport);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Set the number of threads
     */
    public function testThreads() {
        $this->assertInstanceOf('Testy_Util_Parallel_Execute', $this->_object->threads());
        $this->assertEquals(Testy_Util_Parallel_Execute::THREADS, $this->_object->getThreads());
        $this->assertInstanceOf('Testy_Util_Parallel_Execute', $this->_object->threads(2));
        $this->assertEquals(2, $this->_object->getThreads());
    }

    /**
     * Test running methods in parallel
     *
     * @depends testThreads
     */
    public function testRun() {
        $this->assertInstanceOf('Testy_Util_Parallel_Execute', $this->_object->run(array(
            'getName'
        )));
    }

    /**
     * Test getting the result
     *
     * @depends testRun
     */
    public function testGet() {
        $aStack = $this->_object->get();
        $this->assertInternalType('array', $aStack);
        $this->assertEquals(4, count($aStack));
        foreach ($aStack as $oProject) {
            $this->assertInstanceOf(self::TEST_MOCK, $oProject);
        }
    }
}
