<?php
/**
 * Test class for \Testy\Util\Parallel\Transport\SharedMemory.
 * Generated by PHPUnit on 2012-03-24 at 14:59:34.
 */
namespace Testy\Test\Util\Parallel\Transport;

class SharedMemoryTest extends TestAbstract {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_sTestClass = '\\Testy\\Util\\Parallel\\Transport\\SharedMemory';
        parent::setUp();
    }
}
