<?php
/**
 * Test class for Testy_TextUI_Output.
 * Generated by PHPUnit on2011-2012-10-22 at 23:06:51.
 */
class Testy_TextUI_OutputTest extends PHPUnit_Framework_TestCase {

    const TEST_STRING = 'Testy makes testing easier';

    /**
     * Test the error output
     */
    public function testError() {
        $this->expectOutputString('Error: ' . self::TEST_STRING . PHP_EOL);
        Testy_TextUI_Output::error(self::TEST_STRING, false);
    }

    /**
     * Test the info output
     */
    public function testInfo() {
        $this->expectOutputString(self::TEST_STRING . PHP_EOL);
        Testy_TextUI_Output::info(self::TEST_STRING);
    }

    /**
     * Test the write output
     */
    public function testWrite() {
        $this->expectOutputString(self::TEST_STRING);
        Testy_TextUI_Output::write(self::TEST_STRING);
    }
}
